### ISSUE TITLE
Any Tutorial and how to run using rvas results from non staar results like regenie?

### ISSUE THREAD

**Issue by akhilpampana** [xihaoli/MetaSTAAR#6]
Hello,

I have results from staar in one cohort and regenie-based results from other cohorts for putative loss of function and missense variants list. Here are a few questions:

1.) Is there a way to use these to perform meta-analysis or the results are to be from staarpipeline?
2.) Are there any tutorials for this?

Regards
Akhil

**Comment by xihaoli** [comment]
Hi @akhilpampana,

Thanks for reaching out. Yes, we have been preparing a follow-up package that utilizes the `MetaSTAAR` package as a building block and automates all the processes from generating summary stat / cov files to defining the variant sets and performing meta-analysis. The input of the meta-analysis pipeline will be consistent with STAARpipeline. The package is in the final testing stage, and I can add you to the package and tutorial's repositories so that you can make use of the full functionality there.

Let me know your plan.

Best,
Xihao

**Comment by akhilpampana** [comment]
Hello Xihaoli,

Thank you so much for the response, It would be great if you could add me to the github. It would definitely be helpful for the current or future project we plan to work on.

Regards
Akhil

**Comment by xihaoli** [comment]
No problem @akhilpampana! You’ve been invited to the GitHub repos.
